spring:
  profiles:
    active: dev
  application:
    name: yupao-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  servlet:
    context-path: /api
    session:
# 由于 前后端访问地址不同，为了前端能够接收到后端上传的数据，设置domain为localhost (两个地址的公共前缀)
# 其实domain 这里也可以什么都不加，but，加了的话，无论前端的端口怎么改变，接受的都是同一个cookie，不用重新分配cookie
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
